### ISSUE TITLE
`Query engine binary for current platform "rhel-openssl-1.0.x" could not be found.`

### ISSUE THREAD

**Issue by nabi-chan** [nabi-chan-archive/blog-2021#5]
```
ERROR	Error rendering page: pages/index.js. Error:
Error: Query engine binary for current platform "rhel-openssl-1.0.x" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/query-engine-rhel-openssl-1.0.x")

Searched Locations:

  /.prisma/client
  /root/plog/node_modules/@prisma/client
  /
  /var/task/node_modules/.prisma/client
  /var/task
  /tmp/prisma-engines
  /var/task/node_modules/.prisma/client

You already added the platform "rhel-openssl-1.0.x" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma/issues/new
Rendering Next.js error page.
```

MacOS와 Ubuntu에서 Build 했을 때 위와 같은 로그가 출력되며 렌더링이 되지 않음

**Comment by nabi-chan** [comment]
`binaryTargets ["rhel-openssl-1.0.x"]` 을 기준으로 시도

- [x] MacOS에서 테스트 : X
- [x] Ubuntu에서 테스트 : X
- [x] AWS Linux에서 테스트 : X

**Comment by nabi-chan** [comment]
https://github.com/prisma/prisma/issues/4011

`v2.11.0-dev.40` 에서 고쳐졌다고 하는데 뭐가 문제인걸까?

**Comment by nabi-chan** [comment]
`binaryTargets ["native"]` 을 기준으로 시도

- [x] AWS Linux에서 테스트

**Comment by nabi-chan** [comment]
`binaryTargets ["native"]` + build.postBuildCommands: `yarn prisma:generate`로 시도 : X

**Comment by nabi-chan** [comment]
`PRISMA_QUERY_ENGINE_BINARY=./node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x` 를 env에 지정해봄 : X

**Comment by KimPinot** [comment]
S3에 query engine을 업로드하고 테스트 :

**Comment by nabi-chan** [comment]
최근에 1.19.0 버전이 나왔는데 그걸 적용해보면 어떨까?

**Comment by nabi-chan** [comment]
> 최근에 1.19.0 버전이 나왔는데 그걸 적용해보면 어떨까?

직접 버전을 지정해줬는데도 X

**Comment by nabi-chan** [comment]
https://github.com/millsp/prisma-serverless-nextjs/blob/main/serverless.yml 을 적용해보면 어떨까?

**Comment by nabi-chan** [comment]
> https://github.com/millsp/prisma-serverless-nextjs/blob/main/serverless.yml 을 적용해보면 어떨까?

빌드 바로 이전 시점에 api / default lambda에 `node_modules/.prisma/client` 폴더에 schema.prisma와 query-engine을 같이 포함해주는 코드로 보임!

**Comment by KimPinot** [comment]
> > https://github.com/millsp/prisma-serverless-nextjs/blob/main/serverless.yml 을 적용해보면 어떨까?
> 
> 빌드 바로 이전 시점에 api / default lambda에 `node_modules/.prisma/client` 폴더에 schema.prisma와 query-engine을 같이 포함해주는 코드로 보임!

It works!

**Comment by nabi-chan** [comment]
> https://github.com/millsp/prisma-serverless-nextjs/blob/main/serverless.yml 을 적용해보면 어떨까?

It works!
