### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by jeonghyeon-net** [nabi-chan-archive/blog-2021#58]
<img width="272" alt="스크린샷 2021-09-26 오전 9 09 15" src="https://user-images.githubusercontent.com/25793226/134788912-d1c8705a-cc28-49ef-a833-69e8e318cda1.png">

2021.09.26 (일) 09:09:24 기준

홈페이지에 접속이 안되고 있습니다.

사용한 주소는 아래와 같습니다.

[https://blog.pinot.kim/](https://blog.pinot.kim/)

**Comment by nabi-chan** [comment]
제보 감사합니다 🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️
